num_workers: 8
label: 1
remove_diagnostics: true
hu_clip_range: [-150.0, 250.0]
extractor:
  setting:
    binWidth: 25
    normalize: false
    correctMask: true
    geometryTolerance: 1.0e-6
    resampledPixelSpacing: [1.0, 1.0, 1.0]
    interpolator: sitkBSpline
  imageType:
    Original: {}
    LoG:
      sigma: [1.0, 2.0, 3.0]
    Wavelet: {}
  featureClass:
    shape: []
    firstorder: []
    glcm: []
    glrlm: []
    glszm: []
    gldm: []
    ngtdm: []
