backend: nnunetv2_modelfolder
predict_bin: /home/qijunchen/miniconda3/envs/agent/bin/nnUNetv2_predict_from_modelfolder
model_folder: tools/kits23_trained_model
device: cuda:4
checkpoint: checkpoint_best.pth
fold: all
output_label: 2
num_processes_preprocessing: 2
num_processes_segmentation_export: 2
disable_tta: false
mpl_config_dir: tools/nnUNet/.mplconfig
