backend: nnunetv1
nnunet_code_root: tools/nnUNet
nnunet_results_folder: tools/nnUNet/nnUNet_trained_models
device: cuda:6
task_name: Task006_Lung
model: 3d_cascade_fullres
trainer_class_name: nnUNetTrainerV2
cascade_trainer_class_name: nnUNetTrainerV2CascadeFullRes
num_threads_preprocessing: 2
num_threads_nifti_save: 1
disable_tta: false
mpl_config_dir: tools/nnUNet/.mplconfig
