backend: nnunetv2_modelfolder
predict_bin: /home/qijunchen/miniconda3/envs/agent/bin/nnUNetv2_predict_from_modelfolder
model_folder: tools/kits23_trained_model
devices: [cuda:0, cuda:1, cuda:2, cuda:3]
workers_per_gpu: 1
checkpoint: checkpoint_best.pth
fold: all
output_label: 2
num_processes_preprocessing: 2
num_processes_segmentation_export: 2
disable_tta: false
