python_executable: /home/qijunchen/miniconda3/envs/pharaoh/bin/python
model_path: /data/qijun/path-ct/tools/pharaoh/models/kidney_kirc_diamandis/model.onnx
inference_config_path: /data/qijun/path-ct/tools/pharaoh/models/kidney_kirc_diamandis/inference.json
devices: [cuda:0, cuda:1, cuda:2, cuda:3]
workers_per_gpu: 2
batch_size: 32
tumor_probability_threshold: 0.9
overlay_max_size: 1800
