python_executable: /home/qijunchen/miniconda3/envs/gigapath/bin/python
prov_gigapath_code_root: /data/qijun/path-ct/tools/prov-gigapath
batch_size: 256
device: cuda:6
slide_encoder_arch: gigapath_slide_enc12l768d
max_tiles_without_flash_attention: 1024
num_workers: 8
pin_memory: true
prefetch_factor: 2
