nonsynonymous_variants:
  - Missense_Mutation
  - Nonsense_Mutation
  - Frame_Shift_Del
  - Frame_Shift_Ins
  - In_Frame_Del
  - In_Frame_Ins
  - Splice_Site
  - Translation_Start_Site
  - Nonstop_Mutation
top_gene_count: 2000
capture_size: 38.0
